### ISSUE TITLE
Pre-launch notes

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-paypal-smart-buttons#2]
**Pre-launch notes**

PayPal Express Checkout’s Smart Payment Buttons feature gives merchants a variety of ways to customize payment buttons on the checkout page, including the option to pay using Venmo.

**GitHub slug**: eea-paypal-smart-buttons

**PUE product library**: eea-paypal-smart-buttons
**Product page slug**: eea-paypal-smart-buttons
**Recurly plan code**: eea_paypal_smart_buttons+yearly  (note the underscores)

**Recurly live plan URL:** https://eventespresso.recurly.com/plans/eea_paypal_smart_buttons+yearly
**Product page URL**: https://eventespresso.com/product/eea-paypal-smart-buttons
**Documentation page**: https://eventespresso.com/wiki/paypal-express-checkout-smart-payment-buttons-payment-gateway

**Comment by knazart** [comment]
Will leave a note here: this add-on was added to our grunt buildmachine.

**Comment by mnelson4** [comment]
ran github label sync tool (see https://github.com/orgs/eventespresso/teams/staff/discussions/4) so this now has the right labels

**Comment by mnelson4** [comment]
this was released
