### ISSUE TITLE
Payer ID Missing Errors

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-paypal-smart-buttons#24]
## Issue Overview

Sometimes there is an error while paying because somehow we request a payment with no ID.
Reported by @Pebblo on https://github.com/eventespresso/eea-paypal-smart-buttons/issues/3#issuecomment-401120950, but also Nate Sanders from PayPal reported
> 0.6% or 131 calls with Error 10419 (Payer ID Missing)
So it's an intermittent issue.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 

Version of this addon:1.0.0

Version of WordPress:4.9.x

PHP Version:  

Browser used:  

## Steps to Reproduce (for bugs)

@Pebblo reported

> In short, I can select PPSmart, it opens the modal, I log in, then pay and the modal closes but none of the hidden PPSmart inputs are updated. You'll then get an error of the payment failing for technical reasons.

> I'm logging all HTTP connections on the site currently and as theres no payer_id set, the request fails - http://take.ms/pooqt

> No JS errors and if I refresh the page and re-attmpt it usually goes through.

> As far as the new changes to how the payment method looks, I haven't found a problem, switching between payment methods shows the finalize button, this PM does not, it all seems to be working nicely, with the exception of the above.

## Expected Behaviour

It would work.

## Current Behaviour

There are periodic errors. 

## Related Information:

PayPal's sandbox isn't as bullet proof as their production server, but Nate was reporting this error for live users too. I wonder if it's some type of race condition?

**Comment by garthkoyle** [comment]
another report here: https://secure.helpscout.net/conversation/613046838/544390/

**Comment by lorenzocaum** [comment]
This is related to Garth's report. I had a look at their recent registration attempts and it is happening to multiple attendees.

I've resent a payment reminder to see if the payment re-attempt works.

**Comment by lorenzocaum** [comment]
Another report: https://stjohnsnaples.eventsmart.com/wp-admin/admin.php?page=espresso_transactions&action=view_transaction&TXN_ID=52

**Comment by lorenzocaum** [comment]
For Event Smart customers, I'm suggesting to them that they switch to PayPal Express for now while we work through this.

This link will get them PayPal Express complimentary:

https://eventsmart.com/purchase/?slug=paypal-express-integration&plan_type=monthly_plan&coupon=ppefree

**Comment by lorenzocaum** [comment]
Another report: https://secure.helpscout.net/conversation/765302753/609268?folderId=284418

They are using debug at the moment but the "PayPal did not respond with the expected parameters" matches up with what we've seen when the Payer ID issue happens.

**Comment by mnelson4** [comment]
So, https://github.com/eventespresso/eea-paypal-smart-buttons/pull/31 may fix this.
Unfortunately, to my knowledge, it's hard to know for sure because we weren't reproducing consistently.
Although @Pebblo were you able to reproduce this issue enough that your testing could give us reasonable assurance its fixed?

**Comment by lorenzocaum** [comment]
Hey Mike, I looked through the sites that reported this issue to see if I could track this down to Internet Explorer:

On most transactions where this happened, the Transaction Session Details are missing the user agent:

- https://jppcle.eventsmart.com/wp-admin/admin.php?page=espresso_transactions&action=view_transaction&TXN_ID=41
- https://hebrewhelpers13.eventsmart.com/wp-admin/admin.php?page=espresso_transactions&action=view_transaction&TXN_ID=27

On the second one above, the attendee was using an @mac.com email so I think they may have been using a Mac.

I also found this one where it shows Mozilla for the user agent: 

https://stjohnsnaples.eventsmart.com/wp-admin/admin.php?page=espresso_transactions&action=view_transaction&TXN_ID=52

I'm wondering if this might be a timing issue. For example, could it be that if certain things load out of order, then the payer ID is missing because it wasn't requested?

**Comment by mnelson4** [comment]
> I'm wondering if this might be a timing issue. 

Yes, I suspect that's what it is, too. I think when the PayPal modal window closes, we might sometimes be submitting the form **before** the PayPal payment ID gets put that form. (That's because although the code that updates the form comes first, with Javascript's asynchronous nature, I think sometimes be slow and happen later.)

> Hey Mike, I looked through the sites that reported this issue to see if I could track this down to Internet Explorer

Sorry I never mentioned why that might help. That branch also has a few lines from https://github.com/eventespresso/eea-paypal-smart-buttons/tree/BUG/payer-id-missing, which delays the form submission by a full second after the form was updated with the payment ID.

So, the reason that PR might fix this issue **is not** because it adds compatibility with Internet Explorer. It's because it contains code from https://github.com/eventespresso/eea-paypal-smart-buttons/tree/BUG/payer-id-missing

**Comment by garthkoyle** [comment]
@lorenzocaum which customer? Should this ticket be re-opened?

**Comment by mnelson4** [comment]
Yes @lorenzocaum it may be helpful to know which customer. But I don't think this ticket was ever actually closed.
On #32 Tony may have a solution to this, he was going to try to confirm if it solves this issue or not (I'm skeptical it will fix it, but I can't argue with it if it does). If his testing suggests it does, it might be nice to first try it on ES before releasing it in the add-on (that will make reverting it easier if it doesn't actually fix the issue, because I'm anxious it might just add another possible point-of-failure).
If Tony's testing doesn't really indicate it fixes anything, we should add some logging to try to learn more about why this is failing.

**Comment by joshfeck** [comment]
Fixed in #34
