### ISSUE TITLE
"Return to Event Cart" appears above buttons

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-paypal-smart-buttons#25]
## Issue Overview

On https://github.com/eventespresso/eea-paypal-smart-buttons/issues/3#issuecomment-401124192 @Pebblo discovered that: when using MER with PP smart buttons, if you select PP smart buttons, then refresh the page, MER's "Return to Event Cart" button appears ABOVE the smart buttons, which is a bit weird.
Usually that appears well below everything else.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.9.69

Version of this addon:1.0.0

Version of WordPress:4.9.8

PHP Version:  7.1

Browser used:  Firefox

## Steps to Reproduce (for bugs)

Activate MER and this add-on and payment method.
Register for an event
While registering for the event, select this payment method but DO NOT pay...
Refresh the page.
The "REturn to Event Cart" button appears ABOVE the payment smart buttons

## Expected Behaviour

The "Return to Event Cart" button should appear below the smart buttons

## Current Behaviour

Above

**Comment by tn3rb** [comment]
setting complexity estimate at 1 for the time being because this is likely just a filter priority order or something similar. It could turn out to be far more elusive, but we won't know until this gets investigated further.
