### ISSUE TITLE
Under what conditions does Venmo appear?

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-paypal-smart-buttons#26]
Hi Mike, an event organizer asked about Venmo not appearing:

https://secure.helpscout.net/conversation/684192218/576441/

Could you ask Nate for feedback on exactly when Venmo will appear?

I understand from their docs that it is mobile only but are there any other requirements for it to appear?

**Comment by lorenzocaum** [comment]
I also did see this help doc: https://help.venmo.com/hc/en-us/articles/217042888-How-It-Works

...but I'm still not clear on when it appears. The doc sounds like it applies to a mobile app.

**Comment by lorenzocaum** [comment]
This doc sounds like it may fit us more because it talks about an integration rather than a mobile app:

https://www.paypal.com/us/smarthelp/article/venmo-checkout-experience-faq3477

**Comment by mnelson4** [comment]
AFAIK the only conditions should be: they're on mobile, and they're in the USA. Emailed Nate Sanders (cc'd Lorenzo) asking for clarification.

**Comment by lorenzocaum** [comment]
The steps do work!

![img_4353](https://user-images.githubusercontent.com/1079138/46976382-59cc4b00-d097-11e8-895c-0e49803b5655.PNG)

I'm updating our docs for Event Smart and Event Espresso. Then I'll follow up with the customer and post a note about this to the weekly P2.

**Comment by lorenzocaum** [comment]
Alright, I've updated the docs, product pages, followed up with the customer, and posted a note to the weekly p2.
