### ISSUE TITLE
ee_pp_smart_buttons.js needs to be compatible with older browsers

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-paypal-smart-buttons#28]
## Issue Overview

I took a quick look and I see there are some arrow functions & dangling commas in a few places. Maybe this could just be run through the babel compiler?

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 
current release

Version of this addon:
current release
Version of WordPress:
current release

PHP Version:  

Browser used:  
Internet Explorer 11

## Steps to Reproduce (for bugs)

Load up checkout, and click the button to open the PayPal Express buttons. They do not display with IE 11. 

## Related Information:
https://eventespresso.com/topic/paypal-smart-payment-buttons-not-visible-in-ie/

**Comment by mnelson4** [comment]
oh dang, ya thanks. Ya I'm not sure if the babel compiler will make this Javascript work with old browsers, but if so that would be best. I haven't used compilers much... I suppose it's about time!

**Comment by joshfeck** [comment]
@mnelson4 if you want to get a fix for this out sooner (like before you add the build process) you could update the JS from this gist:

https://gist.github.com/joshfeck/4db6a0d895670bd7443ecb5036129d74

**Comment by mnelson4** [comment]
oh thanks, I forgot about that code snippet. But I've got the build process working now, just working through code style issues...

**Comment by Pebblo** [comment]
Looks like this was used for 1.0.3.p so added it to that milestone.

**Comment by Pebblo** [comment]
Doh! This is the issue and not the PR, my bad.
