### ISSUE TITLE
Hidden fields sometimes not updating; MER "Return to Cart" button misplaced

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-paypal-smart-buttons#3]
Chatted with Josh and Tony, and we're in a bit of pickle with the current approach: if we make the button display small, it can't show all the smart buttons or they don't look good in the rest of the layout. If we make them big, when people select an offsite payment method, the "proceed to finalize registration" button is eclipsed by the paypal buttons. 
So we're going to make this more regular: just show a normal paypal button, and only show the smart buttons when it's selected.

**Comment by mnelson4** [comment]
ok this should be good now. Seth tested it, but thinking about it, it might be good to have an extra tester too. @Pebblo wanna take it for a spin? Seeing how I already merged the related PR in I suppose new issues will need to be addressed on new PRs

**Comment by Pebblo** [comment]
Nice job Mike, I like this setup much better, it flows better with EE.

I'm running into issues with this payment method, but I'm not so sure its related to the 'regular payment method' changes.

In short, I can select PPSmart, it opens the modal, I log in, then pay and the modal closes but none of the hidden PPSmart inputs are updated. You'll then get an error of the payment failing for technical reasons.

I'm logging all HTTP connections on the site currently and as theres no payer_id set, the request fails - http://take.ms/pooqt

No JS errors and if I refresh the page and re-attmpt it usually goes through.

As far as the new changes to how the payment method looks, I haven't found a problem, switching between payment methods shows the finalize button, this PM does not, it all seems to be working nicely, with the exception of the above.

Do you want a new issue creating for it?

**Comment by Pebblo** [comment]
Actually, there is a new error specifically from these changes if you use MER. Edge case though.

Add a ticket to the cart, add reg details and proceed to payment options.

Refresh the registration page and you'll now see a 'Return to event cart' button loaded (it doesn't load initially - http://take.ms/ydVVL )

Now select PPSmart - http://take.ms/KYmHt

**Comment by mnelson4** [comment]
@Pebblo can you create separate issues for those two issues? 
The former is hard to debug because I haven't yet reproduced it (even on your site https://ee4dev.pebblo.co.uk). The latter will hopefully just require some CSS tweaks. But I think we may need to address both of those after release. Thoughts?

**Comment by mnelson4** [comment]
Nate Sanders, PayPal rep, said they're seeing the "Payer ID missing" error

> 0.6% or 131 calls with Error 10419 (Payer ID Missing)

So this issue comes up enough to cause a headache, but not enough to make debugging easy...

**Comment by sethshoultes** [comment]
@mnelson4 the pull request for this issue has been merged. Are you still doing anything with this issue?

**Comment by mnelson4** [comment]
Kinda but no anymore. I created https://github.com/eventespresso/eea-paypal-smart-buttons/issues/24 and https://github.com/eventespresso/eea-paypal-smart-buttons/issues/25 for the two specific issues @Pebblo brought up before (and were the reason this was left open).
So there is nothing left to address on this issue that hasn't been recorded on those ones.
