### ISSUE TITLE
If possible, send event name with line item description (or similar)

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-paypal-smart-buttons#30]
Ideally this could be equivalent to the other PayPal options like Express Checkout where the Event Name is sent along with the information to PayPal (in line items or description). This way the event manager can get the name of the event  when looking at the transaction in the paypal account.

**Comment by mnelson4** [comment]
yeah looking over it, I think we're just sending the payment amount.
In order to do this, we need to pass the order description from PHP to the Javascript that creates the payment (and maybe update it if a promotion is applied). 
Here's the PayPal documentation about what we can send: https://developer.paypal.com/docs/api/payments/v1/#definition-transaction

**Comment by mnelson4** [comment]
lol, the v1 of the PayPal Payments REST API, which we use for smart buttons, is deprecated, I just noticed today. See https://developer.paypal.com/docs/api/payments/v1/#definition-transaction

**Comment by mnelson4** [comment]
looking it over, the API change is mostly just that their developers decided to rename things. The overall flow seems basically identical. @joshfeck what do you think of updating the PayPal Smart buttons to v2 because v1 is already deprecated?

**Comment by joshfeck** [comment]
I think we should update because we may need whatever new features they're adding to v2.

**Comment by lorenzocaum** [comment]
An event organizer asked about this here: https://secure.helpscout.net/conversation/883658601/660600/

**Comment by joshfeck** [comment]
I made a separate issue for updating to the v2 API. Updating to v2 may not be needed right away.

This is a feature that more than a few have requested and it would bring parity with other PayPal gateways, so it should be given priority.

**Comment by joshfeck** [comment]
Tracking more feature requests:
https://eventespresso.com/topic-tag/smart-buttons/

**Comment by mnelson4** [comment]
I created https://github.com/eventespresso/eea-paypal-smart-buttons/pull/46 to at least add the order description. Passing all the line item descriptions isn't crazy hard, but it'll probably be a few hours, so if we'd really like a full itemized list I think we could do it separately on another ticket.

**Comment by joshfeck** [comment]
Resolved in #46
