### ISSUE TITLE
Add options to disable specific payment options

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-paypal-smart-buttons#35]
## Issue Overview
Someone wants to remove the "PayPal Credit" option because they think people are confusing "PayPal Credit" with "Pay by Credit card".

Ideally this admin option would include a brief explanation that disabling a specific option will only remove it if PayPal would otherwise add it. In other words, the payment option may not be there for some locations anyway, the setting only ensures that it's never included. 

## Bug report or feature request?

* [ ] Bug
* [x] Feature
* [ ] Neither

**Comment by sethshoultes** [comment]
I see that WooCommerce has a setting to turn this off as well:
https://docs.woocommerce.com/document/paypal-express-checkout/

**Comment by mnelson4** [comment]
Yeah this could be added, and there could be more options than what Woocommerce provides.
Eg, PayPal allows you to disable card, credit, or "sepa" (see https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-funding).
Also, you can disable specific cards (see https://developer.paypal.com/docs/checkout/reference/customize-sdk/#disable-card). 
Also, it seems we can specify a country for debugging (see https://developer.paypal.com/docs/checkout/reference/customize-sdk/#buyer-country). That might only be helpful for us.
What do you think would be best @joshfeck: just provide an option to disable credit like WooCommerce does, or give option to disable card, credit or "sepa" (and possibly even specific credit card types)?

**Comment by joshfeck** [comment]
Only provide an option to disable PayPal Credit.

**Comment by mnelson4** [comment]
Thanks. For my reference here's a related ticket: https://github.com/eventespresso/eea-paypal-smart-buttons/pull/22/files
