### ISSUE TITLE
Release an update on EventEspresso.com

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-paypal-smart-buttons#36]
**Summary**
A customer asked (https://secure.helpscout.net/conversation/782711202/616888/) about an issue with Internet Explorer. It was fixed in #28. 

Could we release an updated version?

**Comment by Pebblo** [comment]
Yeah ill get this update pushed out today.

**Comment by joshfeck** [comment]
Closing this as it's not an issue.
