### ISSUE TITLE
When a decline happens then the gateway response shows as PayPal did not respond with the expected parameters

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-paypal-smart-buttons#37]
**Summary**
This transaction shows a gateway response of PayPal did not respond with the expected parameters:

https://keuper.eventsmart.com/wp-admin/admin.php?page=espresso_transactions&action=view_transaction&TXN_ID=4

If you check the logs, then there are two entries:

![Image 2019-03-14 at 1 17 15 PM](https://user-images.githubusercontent.com/1079138/54377447-7fb44680-465b-11e9-96e3-629a02d603ee.png)

![Image 2019-03-14 at 1 17 32 PM](https://user-images.githubusercontent.com/1079138/54377460-893dae80-465b-11e9-8747-13981af757b8.png)

Is there a way to pull through the declined message and use that for the gateway response?

The reason I ask is an event organizer may look at that transaction screen and think that something is broken when it is actually because of a decline from the card.

**Steps to reproduce**
Not sure

**Reported or seen on**
See notes above

**Comment by lorenzocaum** [comment]
This is the first time that I've seen this so we can use this for monitoring.

**Comment by mnelson4** [comment]
Yeah that's a good point. I think right now the code expects a `transaction` entry under `response_data`, but it isn't there. This is an easy change; most of the work will just be in testing and deploying.
