### ISSUE TITLE
Fix issue where valid payment amount gets refused as "invalid"

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-paypal-smart-buttons#38]
## Issue Overview

I'm replicating an issue reported in the forums where a transaction with a promotion and a partial payment results in a failed API call to PayPal.

To replicate the issue:

1) Start with a new event and set the ticket price to be $466.58
2) Activate the promotions add-on and set a promotion code to $300.00, and set the promotion to global
3) Register for the event (QTY 1 ticket) and input the promotion code, but don't pay yet
4) In a separate browser window or tab, go to the admin > Transactions page and go into the transaction and add a payment of $100.00
5) Go to the other tab with the active registration and refresh the page. At this point the amount owing should be $66.58
6) Select the PayPal Smart buttons PM and attempt to pay.

The unexpected result is you can't pay and a cryptic error message displays for a few seconds.
![Screen Shot 2019-06-03 at 1 47 08 PM](https://user-images.githubusercontent.com/891156/58824816-03525380-860b-11e9-8972-16a0bbb12e2d.png)

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 
master

Version of this addon:
master
Version of WordPress:
WP 5.2

PHP Version:  

Browser used:  
Firefox

**Comment by mnelson4** [comment]
stumbled across a possible issue (it certainly took me forever to confirm it was an issue, I assumed the problem was with my setup for the first while) https://github.com/eventespresso/event-espresso-core/pull/1272#issuecomment-498417242
but I'm reproducing this on EE4.9.80.p

**Comment by mnelson4** [comment]
Oh I see- the amount being sent in this case is `66.58000000000000001`, and PayPal just wants 2 decimal places
