### ISSUE TITLE
Update to v2 of API

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/eea-paypal-smart-buttons#40]
Mentioned in https://github.com/eventespresso/eea-paypal-smart-buttons/issues/30#issuecomment-488352097

**Comment by joshfeck** [comment]
Reopening this for now. We may end up doing an integration with PayPal's other new platform. If we do that, then maybe we won't end up updating the API for the smart buttons add-on.

**Comment by garthkoyle** [comment]
Docs for PayPal Commerce (supposed to condense and succeed most PayPal products): https://developer.paypal.com/docs/platforms/

**Comment by garthkoyle** [comment]
https://p2.eventespresso.com/2020/05/19/evaluating-paypal-commerce-as-a-new-integration/
