### ISSUE TITLE
Show "Debug mode is turned on" message when debug is enabled

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/eea-paypal-smart-buttons#42]
**Summary**
In this issue (https://github.com/eventespresso/eventsmart.com-website/issues/530), I've been tracking reports of customers who enable debug mode and then don't turn it off so they start receiving payments but they aren't actually getting any funds.

What we've tried?

- I updated the help doc with screenshots on where to click: https://help.eventsmart.com/article/286-paypal-express-checkout-smart-payment-buttons-payment-gateway#locate
- The email notification that is sent after someone adds the feature upgrade was also updated.

I noticed that PayPal Smart Buttons doesn't show a debug message when debug is on. I think this could help because if an event organizer forgets to disable debug, then an attendee is likely to bring this to their attention (we saw this with the payment ID issue):

https://github.com/eventespresso/eventsmart.com-website/issues/530#issuecomment-526615752

Could we add a similar message as other gateways that shows that debug mode is enabled?

**Comment by mnelson4** [comment]
Yes that would be an easy addition. Its exclusion was an oversight of mine.
