### ISSUE TITLE
Smart buttons don't appear if Stripe also active

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/eea-paypal-smart-buttons#48]
## Issue Overview

If you activate Stripe too, when you initially select PayPal Smart Buttons, the buttons don't appear. But with Stripe deactivated, they work fine. See this video: https://drive.google.com/file/d/1xm7dsWh5R3Q2LEq3iGAS0XjBivzxlq9E/view

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE core: 4.10.3.rc.026

Version of this addon:1.1.9.rc.000

Version of WordPress:5.3

PHP Version:  7.1

Browser used: Firefox

## Steps to Reproduce (for bugs)

* Activate Stripe and PayPal Smart Buttons
* Register for an event
* Select PayPal Smart Buttons. 

See https://drive.google.com/file/d/1xm7dsWh5R3Q2LEq3iGAS0XjBivzxlq9E/view

## Expected Behaviour

The buttons should appear just the same.

## Current Behaviour

The buttons don't appear.

## Related Information:

I discovered this while testing https://github.com/eventespresso/event-espresso-core/pull/1587 of EE core, but the issue is reproducible on current EE core master

**Comment by joshfeck** [comment]
It looks like it's only an issue if Stripe Elements is selected, the buttons are displayed if Stripe Checkout is selected.

I'm also seeing this JS error in the console when Stripe Elements + PayPal Smart buttons are loaded on the same page:

```TypeError: this.paymentForm.off is not a function /eea-stripe-gateway/assets/dist/eventespresso-stripe-elements.c612210c583c32cf7cfe.dist.js?ver=1.1.9.rc.002 line 460```

So maybe this will require a PR for the Stripe add-on?

**Comment by joshfeck** [comment]
closing this since there's a PR in another repo to fix this
