### ISSUE TITLE
Shorten Payment Type Text on Thank You page

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/eea-paypal-smart-buttons#7]
The current text that is output on the Thank You page looks a little too long:
"PayPal Express Checkout with Smart Buttons"

In this screenshot, you can see how it compares to just "PayPal Express" when using that payment option.

https://www.screencast.com/t/HdB9s9xA

I think we should shorten the Payment Type test to read: "PayPal Express Checkout"

I don't think it should hold up launch but should probably be updated soon.

**Comment by mnelson4** [comment]
Created https://github.com/eventespresso/event-espresso-core/pull/558 for the EE core changes needed to make this happen

**Comment by mnelson4** [comment]
PR was closed
